# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cards.proto',
  package='cards',
  serialized_pb='\n\x0b\x63\x61rds.proto\x12\x05\x63\x61rds\"l\n\nCardConfig\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0f\n\x07\x63\x61rd_id\x18\x02 \x02(\r\x12\x1c\n\x14\x63\x61pability_bitvector\x18\x03 \x02(\r\x12\n\n\x02ip\x18\x04 \x02(\t\x12\x15\n\ris_registered\x18\x05 \x02(\x08\"8\n\x0e\x43\x61rdConfigList\x12&\n\x0b\x63\x61rd_config\x18\x01 \x03(\x0b\x32\x11.cards.CardConfig')




_CARDCONFIG = descriptor.Descriptor(
  name='CardConfig',
  full_name='cards.CardConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='cards.CardConfig.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='card_id', full_name='cards.CardConfig.card_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability_bitvector', full_name='cards.CardConfig.capability_bitvector', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='cards.CardConfig.ip', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_registered', full_name='cards.CardConfig.is_registered', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=130,
)


_CARDCONFIGLIST = descriptor.Descriptor(
  name='CardConfigList',
  full_name='cards.CardConfigList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='card_config', full_name='cards.CardConfigList.card_config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=188,
)

_CARDCONFIGLIST.fields_by_name['card_config'].message_type = _CARDCONFIG
DESCRIPTOR.message_types_by_name['CardConfig'] = _CARDCONFIG
DESCRIPTOR.message_types_by_name['CardConfigList'] = _CARDCONFIGLIST

class CardConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CARDCONFIG
  
  # @@protoc_insertion_point(class_scope:cards.CardConfig)

class CardConfigList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CARDCONFIGLIST
  
  # @@protoc_insertion_point(class_scope:cards.CardConfigList)

# @@protoc_insertion_point(module_scope)
