# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='rabbitmq.proto',
  package='rabbitmq',
  serialized_pb='\n\x0erabbitmq.proto\x12\x08rabbitmq\"%\n\x08RabbitMQ\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t')




_RABBITMQ = descriptor.Descriptor(
  name='RabbitMQ',
  full_name='rabbitmq.RabbitMQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='rabbitmq.RabbitMQ.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='args', full_name='rabbitmq.RabbitMQ.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['RabbitMQ'] = _RABBITMQ

class RabbitMQ(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RABBITMQ
  
  # @@protoc_insertion_point(class_scope:rabbitmq.RabbitMQ)

# @@protoc_insertion_point(module_scope)
