# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='analysis.proto',
  package='analysis',
  serialized_pb='\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\x90\x01\n\x0c\x41nalysisInfo\x12\x12\n\nlophi_name\x18\x01 \x02(\t\x12\x14\n\x0cmachine_type\x18\x02 \x02(\r\x12\x14\n\x0cmachine_name\x18\x03 \x02(\t\x12\x1a\n\x12volatility_profile\x18\x04 \x02(\t\x12\x0f\n\x07\x63reated\x18\x05 \x02(\x02\x12\x13\n\x0b\x61nalysis_id\x18\x06 \x02(\r\"8\n\x0c\x41nalysisList\x12(\n\x08\x61nalysis\x18\x01 \x03(\x0b\x32\x16.analysis.AnalysisInfo')




_ANALYSISINFO = descriptor.Descriptor(
  name='AnalysisInfo',
  full_name='analysis.AnalysisInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='lophi_name', full_name='analysis.AnalysisInfo.lophi_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='machine_type', full_name='analysis.AnalysisInfo.machine_type', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='machine_name', full_name='analysis.AnalysisInfo.machine_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='volatility_profile', full_name='analysis.AnalysisInfo.volatility_profile', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='created', full_name='analysis.AnalysisInfo.created', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='analysis_id', full_name='analysis.AnalysisInfo.analysis_id', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=173,
)


_ANALYSISLIST = descriptor.Descriptor(
  name='AnalysisList',
  full_name='analysis.AnalysisList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='analysis', full_name='analysis.AnalysisList.analysis', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=175,
  serialized_end=231,
)

_ANALYSISLIST.fields_by_name['analysis'].message_type = _ANALYSISINFO
DESCRIPTOR.message_types_by_name['AnalysisInfo'] = _ANALYSISINFO
DESCRIPTOR.message_types_by_name['AnalysisList'] = _ANALYSISLIST

class AnalysisInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANALYSISINFO
  
  # @@protoc_insertion_point(class_scope:analysis.AnalysisInfo)

class AnalysisList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANALYSISLIST
  
  # @@protoc_insertion_point(class_scope:analysis.AnalysisList)

# @@protoc_insertion_point(module_scope)
