# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='machines.proto',
  package='machines',
  serialized_pb='\n\x0emachines.proto\x12\x08machines\"9\n\rMachineConfig\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1a\n\x12volatility_profile\x18\x02 \x02(\t\"S\n\x07Machine\x12\x11\n\tALLOCATED\x18\x01 \x02(\x05\x12\'\n\x06\x63onfig\x18\x02 \x02(\x0b\x32\x17.machines.MachineConfig\x12\x0c\n\x04type\x18\x03 \x02(\x05\"1\n\x0bMachineList\x12\"\n\x07machine\x18\x01 \x03(\x0b\x32\x11.machines.Machine')




_MACHINECONFIG = descriptor.Descriptor(
  name='MachineConfig',
  full_name='machines.MachineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='machines.MachineConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='volatility_profile', full_name='machines.MachineConfig.volatility_profile', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=85,
)


_MACHINE = descriptor.Descriptor(
  name='Machine',
  full_name='machines.Machine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ALLOCATED', full_name='machines.Machine.ALLOCATED', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config', full_name='machines.Machine.config', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='machines.Machine.type', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=170,
)


_MACHINELIST = descriptor.Descriptor(
  name='MachineList',
  full_name='machines.MachineList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='machine', full_name='machines.MachineList.machine', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=172,
  serialized_end=221,
)

_MACHINE.fields_by_name['config'].message_type = _MACHINECONFIG
_MACHINELIST.fields_by_name['machine'].message_type = _MACHINE
DESCRIPTOR.message_types_by_name['MachineConfig'] = _MACHINECONFIG
DESCRIPTOR.message_types_by_name['Machine'] = _MACHINE
DESCRIPTOR.message_types_by_name['MachineList'] = _MACHINELIST

class MachineConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MACHINECONFIG
  
  # @@protoc_insertion_point(class_scope:machines.MachineConfig)

class Machine(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MACHINE
  
  # @@protoc_insertion_point(class_scope:machines.Machine)

class MachineList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MACHINELIST
  
  # @@protoc_insertion_point(class_scope:machines.MachineList)

# @@protoc_insertion_point(module_scope)
