Document: lophi-disk-introspection-server
Title: Debian lophi-disk-introspection-server Manual
Author: <insert document author here>
Abstract: This manual describes what lophi-disk-introspection-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lophi-disk-introspection-server/lophi-disk-introspection-server.sgml.gz

Format: postscript
Files: /usr/share/doc/lophi-disk-introspection-server/lophi-disk-introspection-server.ps.gz

Format: text
Files: /usr/share/doc/lophi-disk-introspection-server/lophi-disk-introspection-server.text.gz

Format: HTML
Index: /usr/share/doc/lophi-disk-introspection-server/html/index.html
Files: /usr/share/doc/lophi-disk-introspection-server/html/*.html
